all:
	curl -L https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/json/petstore-simple.json > petstore.json
	curl -L https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json > slack.json
	curl -L https://raw.githubusercontent.com/gothinkster/realworld/main/api/swagger.json > realworld.json
