name: PR

on:
  merge_group:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  Commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
        with:
          configFile: .commitlintrc.yml

  Title:
    name: Semantic PR Title
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      pull-requests: read

    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            did not match the configured pattern. Please ensure that the subject
            does not start with an uppercase character.
          validateSingleCommit: false
