name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  Please:
    runs-on: ubuntu-latest

    steps:
      - id: release
        name: Release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE_ACTION }}
